- server/config.js
User name was postgres which does not work with CYF laptop setup.
> Change DB username to app_user

- client/package-lock.json
- client/package.json
- client/src/api/opportunities.js
- client/src/components/About.js
- client/src/components/NavBar.js
- client/src/components/NewOpportunityForm.js
- client/src/index.js
- server/api/cities.js
- server/api/opportunities.js
- server/api/skills.js
- server/api/status.js
- server/api/users.js
- server/services/database/users.js
1-updated the menu by creating new component NavBar .
2- removed semantic ui calendar  which i installed by mistake at last pr.
3-changed the layout of the New Opportunity form as mentioned on the trello card comment .
4- added grid around the whole application. 
5-changed the id to user_id in api/users.
> Update the menu  and add grid

- client/src/api/opportunities.js
- client/src/components/NavBar.js
- client/src/components/NewOpportunityForm.js
- client/src/components/Status.js
- client/src/index.css
- client/src/index.js
- package-lock.json
- package.json
- server/api/cities.js
- server/api/index.js
- server/api/opportunities.js
- server/api/opportunitySkills.js
- server/api/skills.js
- server/services/database/opportunities.js
- server/services/database/opportunitySkills.js
- server/services/database/users.js
1- added skills to opportunity skills table
2- added messages for success and error  response for the opportunity form
3- added some comments in deffernt files
4- sorry for adding all commits at one commit but it destruct me if i breakdown my work i didn't manage to do that i will keeb trying
> Add skills to opportunity_skills T

- client/src/api/auth.js
- client/src/components/Home.js
- client/src/components/Login.js
- client/src/components/NavBar.js
- client/src/index.js
Login and Logout displayed
Login form displayed
Get error when the info is not convenient
> sigin form

- client/src/components/Login.js
> Add forgot password link

- client/src/components/Home.js
- client/src/components/NavBar.js
- client/src/components/Routes.js
- client/src/index.js
1- resored changes happened during the PR and merge before my pr ,
2- the group member had a merge conflicts and what happened that the current changes are accepted and discareded the upcoming changes
3- i solved the problem and ready for merge
> Solve problem happened during merge

- client/src/components/OpportunitiesList.js
Filter by Job Type and Skills.
> Filter by Job Type and Skills

- client/src/components/Routes.js
Remove duplication on Company Profile page
> Remove duplication on Company Profile page

- client/src/api/applicantProfile.js
- client/src/components/ApplicantProfile.js
- server/api/applicantProfile.js
- server/api/applicantSkills.js
- server/api/index.js
- server/api/opportunitySkills.js
- server/services/database/applicantProfile.js
- server/services/database/applicantSkills.js
- server/services/database/opportunitySkills.js
to solve a bug during registration and did some improvements to the applicant profile
> Solve applicant registration bug

- client/src/components/OpportunitiesCard.js
- client/src/components/OpportunitiesList.js
Display error message when no opportunity card matches
> Fix a bug, refactor OpportunitiesList components

- client/src/components/ApplicantRegister.js
- client/src/components/OpportunitiesList.js
- client/src/components/OpportunityTypeCard.js
- client/src/components/ValidatedFormFields.js
- client/src/utils/formValidation.js
- client/src/utils/formValidation.test.js
1- made all the cards of the opportunity List all the same size and alignment with each others
2- crated a separate component for validating applicant register inputs
3- improved the way  in which the error messages displayed with each field
> Improve Applicant Register Validation

- client/src/components/ApplicantProfile.js
- client/src/components/NavBar.js
on the log in the token and user data is saved to local storage
when a user is logged in and click on my profile button at the menu it shows the logged-in user profile
when log out the saved data of the user and token will be removed from the local storage
> Display logged user profile

- client/src/components/ApplicantProfile.js
- client/src/components/Login.js
- client/src/components/NavBar.js
- client/src/components/OpportunityView.js
- client/src/utils/storage.js
> Refactor local storage code

- client/src/api/applicants.js
- client/src/components/ApplicantsCard.js
- client/src/components/ApplicantsList.js
- server/api/applicantSkills.js
- server/db/populate-db.sql
Wanted to commit those changes before it becomes a long PR, filter is not complete.
> Add applicants skills

- client/src/api/companies.js
- client/src/components/CompanyProfile.js
- client/src/components/NewOpportunityForm.js
- server/api/companies.js
- server/services/database/companies.js
1-Removed Hardcoded company Id in creating new opportunity by getting the id of opportunity id from the database bypassing the user-id
and using it at the state to create the opportunity
2- at company profile added a condition in case there is no company Logo it will display an empty image
> Remove hard coded company id at new opportunity

- client/src/api/applicants.js
- client/src/api/editApplicantProfile.js
- client/src/components/ApplicantProfile.js
- client/src/components/ApplicantProfileContent.js
- client/src/components/EditApplicantProfile.js
- client/src/components/ProfileOptionsButton.js
- server/api/applicantSkills.js
- server/api/editApplicantProfile.js
- server/api/index.js
- server/services/database/applicantProfile.js
- server/services/database/applicantSkills.js
- server/services/database/editApplicantProfile.js
Edit the Applicant profile 
1- create 2 components one to display the details and the other to edit 
2- get the data to be displayed  at EditApplicantProfile
3-edit the ApplicantDetails "name, city, cvLink, About"
4- Remove the current skills  from database
5- add the newly selected skills to the database
> Edit applicant profile

- client/src/components/Home.js
- client/src/components/MatchingApplicantsAndOppotunities.js
- package-lock.json
- package.json
- server/db/populate-db.sql
> Match applicant skills with opportunity skills without styles

- client/src/api/adminProfile.js
- client/src/components/AdminProfiles.js
- client/src/components/ApplicantProfile.js
- client/src/components/ApplicantsCard.js
- client/src/components/ApplicantsList.js
- client/src/components/Routes.js
- client/src/components/SideBar.js
- server/api/adminProfile.js
- server/api/applicantProfile.js
- server/api/index.js
- server/db/populate-db.sql
- server/services/database/adminProfile.js
when Applicant register the profile will be sitting by default  as pending and with this pr it will not be shown till the admin approve it
> Admin approval For Applicant Profiles

- client/src/components/ApplicantProfileContent.js
- client/src/components/ApplicantRegister.js
- client/src/components/EditApplicantProfile.js
- server/api/applicantProfile.js
- server/api/editApplicantProfile.js
- server/db/populate-db.sql
- server/db/recreate-schema.sql
- server/services/database/applicantProfile.js
- server/services/database/editApplicantProfile.js
1-add the image field to applicant register and Edit applicant front end and backend
2- display the image at the applicant profile
3- display the image source at the  edit applicant page
4- add profile picture column at DB table  and to the Populate at the current  applicants samples
> Add image to applicant profile

- client/src/api/opportunities.js
- client/src/components/Login.js
- client/src/components/OpportunitiesList.js
- client/src/components/OpportunityCard.js
- server/services/database/opportunities.js
when company opens opportunities list can see the Edit and delete at the company's card opportunities cards
> Add edit delete buttons to comapny opportunity

- client/src/components/ApplicantRegister.js
- client/src/components/ApplicantsList.js
- client/src/components/EditApplicantProfile.js
- client/src/components/NewOpportunityForm.js
- client/src/components/OpportunitiesList.js
- server/db/cities.sql
- server/db/populate-db.sql
- server/db/seed-db.js
- server/db/skills.sql
created two sql files to Cities and Skills
> Add cities and skills to db

- client/src/components/Company/CompanyProfile.js
- client/src/components/Company/CompanyProfileContent.js
- client/src/components/Opportunities/OpportunitiesList.js
- client/src/components/Opportunities/OpportunityCard.js
- client/src/components/Opportunities/OpportunityView.js
- server/services/database/opportunities.js
- server/services/database/opportunitySkills.js
Company Profile and Opportunity list
> Add edit  Opportunity functionality to
